#!/usr/bin/env bash

export VERSION=${VERSION:-3.1.0}

nightly() {
  export VERSION=$VERSION+"$(date +%Y.%m.%d%H%M%S)"
  export MIX_ENV="nightly"
  export RELEASE_ENV="nightly"

  mix release --env="$RELEASE_ENV"
  if [[ "$?" != 0 ]]; then
    echo "Nightly Failed To Build"
    exit 1
  fi

  TAR="_build/nightly/rel/animu/releases/$VERSION/animu.tar.gz"

  scp "$TAR" cthulhu:"/opt/animu/nightly.tar.gz"
  ssh cthulhu "/opt/animu/scripts/deploy" "nightly" "$VERSION"
}

release() {
  if [[ -z "$1" ]]; then
    echo "Release Requires Version Number"
    exit 1
  fi

  export VERSION="$1"
  export MIX_ENV="prod"
  export RELEASE_ENV="prod"

  mix release --env="$RELEASE_ENV"
  if [[ "$?" != 0 ]]; then
    echo "Release Failed To Build"
    exit 1
  fi

  TAR="_build/nightly/rel/animu/releases/$VERSION/animu.tar.gz"

  scp "$TAR" cthulhu:"/opt/animu/release.tar.gz"
  ssh cthulhu "/opt/animu/scripts/deploy" "release" "$VERSION"
}

# Options
case $1 in
  nightly)
    nightly
    ;;
  release)
    release "$2"
    ;;
  *)
    echo "Usage: deploy {nightly | release} [version]"
    ;;
esac


