#!/usr/bin/env bash

TOKEN="$(cat ~/var/auth/animu-token)"
URL=${URL:-http://localhost:4000}

curl -s -X GET \
     -H "Authorization: $TOKEN" \
     -H "Accept: application/json" \
     "$URL/api/v1/$1" \
| jq '.'
