#!/usr/bin/env bash

LOGIN=${1:-login.json}

curl -s -X POST \
     -H "Content-Type: application/json" \
     -d "$(cat $LOGIN)" \
     http://localhost:4000/api/v1/session \
| jq -r .jwt > token
#| python -c "import sys, json; print json.load(sys.stdin)['jwt']" > token
