#!/usr/bin/env bash

TOKEN="$(cat token)"
URL=${URL:-http://localhost:4000}

curl -s -X PATCH \
     -H "Authorization: $TOKEN" \
     -H "Content-Type: application/json" \
     -d "$(cat $2)" \
     "$URL/api/v1/$1"
#| jq '.'
echo ""

