#!/usr/bin/env bash

TOKEN="$(cat ~/var/auth/animu-token)"
URL=${URL:-http://localhost:4000}

curl -s -X PATCH \
     -H "Authorization: $TOKEN" \
     -H "Content-Type: application/json" \
     -d "$(cat $2)" \
     "$URL/api/$1" \
\
| jq -R '. as $raw | try fromjson catch $raw'

